Fix failure of const2.C.
This test is not adapted to the difference in output betweem LD and GOLD,
namely that gold prints an extra newline before we get to 'i':

gold:
/tmp/ccEbCXyD.o:const2.C:p':
(.sdata+0x0): error: undefined reference to 'A<int>::i'
collect2: error: ld returned 1 exit status

ld:
/tmp/cc4MSIIi.o:(.sdata+0x0): undefined reference to `A<int>::i'
collect2: error: ld returned 1 exit status

gcc/testsuite/

  * g++.old-deja/g++.pt/const2.C: Prune extra line printed by GOLD.

(cherry picked from commit 5f04c684361b10075bcdfdb15f0566d9058743d4)